spaces

diff --git a/config/Makefile b/config/Makefile
--- a/config/Makefile
+++ b/config/Makefile
@@ -12,19 +12,19 @@ sizeof = \
       int main() {\
          return (int)sizeof($2);\
       }" | $(CC) -xc - $3 -o /tmp/$2.$$$$; then\
-	echo "Ok."; \
-	chmod u+x /tmp/$2.$$$$;\
-	/tmp/$2.$$$$; printf "(define sizeof:$2 %d)" $$? >$@;\
-	rm -f /tmp/$2.$$$$;\
+      echo "Ok."; \
+      chmod u+x /tmp/$2.$$$$;\
+      /tmp/$2.$$$$; printf "(define sizeof:$2 %d)" $$? >$@;\
+      rm -f /tmp/$2.$$$$;\
    else\
-	echo "\033[0;31mError.\033[0m";\
-	printf 0 > $@;\
+      echo "\033[0;31mError.\033[0m";\
+      printf 0 > $@;\
    fi
 
 config/XEvent:
-	   $(call sizeof, <X11/Xutil.h>,XEvent)
+	$(call sizeof, <X11/Xutil.h>,XEvent)
 config/XVisualInfo:
-	   $(call sizeof, <X11/Xutil.h>,XVisualInfo)
+	$(call sizeof, <X11/Xutil.h>,XVisualInfo)
 
 # ...
 
