global tests mark "passed/failed" fixed

diff --git a/doc/reference/check b/doc/reference/check
--- a/doc/reference/check
+++ b/doc/reference/check
@@ -16,17 +16,20 @@ define check-reference
 	      printf \|$(ok) ;\
 	   else \
 	      printf \|$(fail);\
-	      touch $(FAILED);\
+	      echo $1: $^ >> $(FAILMARK);\
 	   fi
 endef
 
+.SILENT: check-reference
+check-reference: FAILMARK:=$(shell mktemp -u tmp/fail.reference.XXXXXXXXX)
+
 check-reference: olvm-binaries
 check-reference: $(wildcard doc/reference/*.md)
-	@echo " "
-	@echo "# CHECK REFERENCE"
-	@$(eval F1LEN=$(shell for F in $(TEST_FILES); do echo $${#F}; done |sort -n| tail -1))
-	@$(call table-header, $(F1LEN))
-	@for F in $(filter %.md,$^); do \
+	echo " "
+	echo "# CHECK REFERENCE"
+	$(eval F1LEN=$(shell for F in $(TEST_FILES); do echo $${#F}; done |sort -n| tail -1))
+	$(call table-header, $(F1LEN))
+	for F in $(filter %.md,$^); do \
        printf "|%-$(F1LEN)s " "$$F" |sed 's/ /*/; s/ /./g; s/*/ /' ;\
 	   # i386 linux \
 	   if [ "$(DEV_MACHINE)$(HAVE_32CDEFS)" = "11" ]; then $(call check-reference,tmp/olvm-i386-debug,$$F); fi ;\
@@ -51,5 +54,7 @@ check-reference: $(wildcard doc/reference/*.md)
 	   if [ "$(DEV_MACHINE)" = "0" ]; then $(call check-reference,tmp/olvm-native-release,$$F); fi ;\
 	   echo "|";\
 	done
-	@if [ -e $(FAILED) ] ;then rm -f $(FAILED); exit 1 ;fi
-	@echo "$(green)passed!$(done)"
+	case `test -f $(FAILMARK); echo $$?` in\
+	   0) echo "$(red)FAILED!$(done)";;\
+	   1) echo "$(green)passed!$(done)";;\
+	esac
